### ISSUE TITLE
Method not found exception

### ISSUE THREAD

**Issue by debarshri** [perwendel/spark-template-engines#26]
I get this exception
[qtp1652802766-19] WARN org.eclipse.jetty.server.HttpChannel - //localhost:9090/
java.lang.NoSuchMethodError: com.google.common.base.Platform.systemNanoTime()J
	at com.google.common.base.Ticker$1.read(Ticker.java:60)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2221)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at com.github.jknack.handlebars.cache.GuavaTemplateCache.get(GuavaTemplateCache.java:69)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:431)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:374)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:360)
	at spark.template.handlebars.HandlebarsTemplateEngine.render(HandlebarsTemplateEngine.java:75)
	at io.farragolabs.bugbuster.route.BugBusterHome.handle(BugBusterHome.java:30)
	at io.farragolabs.bugbuster.route.BugBusterHome.handle(BugBusterHome.java:11)
	at spark.RouteImpl$1.handle(RouteImpl.java:58)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)

**Comment by debarshri** [comment]
It happens when you have guava 18 in your dependency.
