### ISSUE TITLE
java.io.FileNotFoundException Template not found

### ISSUE THREAD

**Issue by anxiaoyi** [perwendel/spark-template-engines#53]
```java
java.lang.IllegalArgumentException: java.io.FileNotFoundException: Template index.ftl not found.
	at spark.template.freemarker.FreeMarkerEngine.render(FreeMarkerEngine.java:74)
	at spark.TemplateViewRouteImpl$1.render(TemplateViewRouteImpl.java:61)
	at spark.TemplateViewRouteImpl$1.render(TemplateViewRouteImpl.java:58)
	at spark.TemplateViewRouteImpl.render(TemplateViewRouteImpl.java:86)
	at spark.http.matching.Routes.execute(Routes.java:62)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:128)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: Template index.ftl not found.
	at freemarker.template.Configuration.getTemplate(Configuration.java:580)
	at freemarker.template.Configuration.getTemplate(Configuration.java:543)
	at spark.template.freemarker.FreeMarkerEngine.render(FreeMarkerEngine.java:69)
	... 20 more
```

**Comment by hatakawas** [comment]
Same problem.
